# UwU Dark Theme - Matches Emacs uwu-theme

cursor                  #C26F6F
cursor_text_color       #232A2C

foreground              #C5C8C9
background              #131A1C

selection_foreground    #C5C8C9
selection_background    #2F3638

# Black
color0   #1B2224
color8   #232A2C

# Red
color1   #F65B5B
color9   #C26F6F

# Green
color2   #6BB05D
color10  #8DC776

# Yellow
color3   #E59E67
color11  #E7AC7E

# Blue
color4   #53A7BF
color12  #6CBAD1

# Magenta
color5   #B185DB
color13  #BB8FE5

# Cyan
color6   #51A39F
color14  #6DB0AD

# White
color7   #C4C4C4
color15  #C5C8C9

# Tab bar
active_tab_foreground   #C5C8C9
active_tab_background   #2F3638
inactive_tab_foreground #828A8C
inactive_tab_background #131A1C
